name: repo dispatch example

on: [repository_dispatch]

permissions:
    actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3            
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Echo github event
        run: |
          ./scripts/mdx.py
        with:
          args: $CLIENT_PAYLOAD

        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
