name: repo dispatch example

on: [repository_dispatch]

permissions:
    actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dispatch trigger
        if: github.event.action == TEST_EVENT
        run: |
          echo "repository_dispatch triggered"
