name: repo dispatch example

on: [repository_dispatch]

permissions:
    actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3            
      - uses: actions/setup-python@v4
      - name: execute py script
        run: |
          python ./scripts/mdx.py $CLIENT_PAYLOAD

        env:
          CLIENT_PAYLOAD: ${{ github.event.client_payload }}
