name: repo dispatch example

on: [repository_dispatch]

permissions:
    actions: write
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3            
        with:
          fetch-depth: 0
      - name: Get Repo changes
        run: |
          git pull
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Execute py script
        run: python ./scripts/mdx.py -d '${{ toJson(github.event.client_payload) }}'
        env:
          CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      - name: Adding the new article
        run: |
          git config --global user.name "Bruno Frigeri"
          git config --global user.email "bpiraja97@gmail.com"
          git add \*.mdx
          git commit -a -m "merge: add new article to blog"
          git push
