name: repo dispatch example

on: [repository_dispatch]

permissions:
    actions: write
    repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3            
        with:
          fetch-depth: 0
      - name: Get Repo changes
        run: |
          git pull
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Execute py script
        run: echo ${{ toJson(github.event) }}
        env:
          CLIENT_PAYLOAD: ${{ toJson(github.event) }}
      # - name: Adding the new article
      #   run: |
      #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
      #     git config --global user.email "bpiraja97@gmail.com"
      #     git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      #     git push
        # uses: EndBug/add-and-commit@v9
        # with:
        #   add: '*.mdx'
        #   message: 'merge: add new article to blog'
